DROP TABLE IF EXISTS movies;
DROP TABLE IF EXISTS stocks;

CREATE TABLE movies (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  year TEXT NOT NULL,
  img_url TEXT NOT NULL
);

CREATE TABLE stocks (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ticker TEXT NOT NULL,
  company TEXT NOT NULL,
  is_etf BOOLEAN NOT NULL
)